# Generated by Django 3.2.13 on 2022-07-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='car_detector', max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('image_labeled', models.ImageField(upload_to='')),
                ('detector_model', models.CharField(choices=[('frcnn-resnet', 'Faster R-CNN with ResNet50 backbone'), ('frcnn-mobilenet', 'Faster R-CNN with MobileNetv3 backbone'), ('retinanet', 'RetinaNet with ResNet50 backbone'), ('ssd-vgg16', 'SSD with VGG16 backbone')], max_length=200)),
                ('num_of_objects', models.CharField(default='failed', max_length=200)),
            ],
            options={
                'db_table': 'myapp_image',
            },
        ),
    ]
